# Generated by Django 4.2.4 on 2023-08-08 22:15

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.upload_to_file),
        ),
    ]
